name: rick_and_morty_api
description: A new Flutter package project.
version: 0.1.1
homepage: https://github.com/Yash-Garg/RickandMorty-Dart-Wrapper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  lints: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
